//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace TrackPadSilverlight.WindowsPhoneMouseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.anotherpart.com", ConfigurationName="WindowsPhoneMouseService.IMouseEvent")]
    public interface IMouseEvent {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://www.anotherpart.com/IMouseEvent/MouseMoveTuple")]
        System.IAsyncResult BeginMouseMoveTuple(string DwFlag, string Dx, string Dy, string DwData, string DwExtraInfo, System.AsyncCallback callback, object asyncState);
        
        void EndMouseMoveTuple(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMouseEventChannel : TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MouseEventClient : System.ServiceModel.ClientBase<TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent>, TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent {
        
        private BeginOperationDelegate onBeginMouseMoveTupleDelegate;
        
        private EndOperationDelegate onEndMouseMoveTupleDelegate;
        
        private System.Threading.SendOrPostCallback onMouseMoveTupleCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MouseEventClient() {
        }
        
        public MouseEventClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MouseEventClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MouseEventClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MouseEventClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> MouseMoveTupleCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent.BeginMouseMoveTuple(string DwFlag, string Dx, string Dy, string DwData, string DwExtraInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMouseMoveTuple(DwFlag, Dx, Dy, DwData, DwExtraInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent.EndMouseMoveTuple(System.IAsyncResult result) {
            base.Channel.EndMouseMoveTuple(result);
        }
        
        private System.IAsyncResult OnBeginMouseMoveTuple(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string DwFlag = ((string)(inValues[0]));
            string Dx = ((string)(inValues[1]));
            string Dy = ((string)(inValues[2]));
            string DwData = ((string)(inValues[3]));
            string DwExtraInfo = ((string)(inValues[4]));
            return ((TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent)(this)).BeginMouseMoveTuple(DwFlag, Dx, Dy, DwData, DwExtraInfo, callback, asyncState);
        }
        
        private object[] OnEndMouseMoveTuple(System.IAsyncResult result) {
            ((TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent)(this)).EndMouseMoveTuple(result);
            return null;
        }
        
        private void OnMouseMoveTupleCompleted(object state) {
            if ((this.MouseMoveTupleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MouseMoveTupleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MouseMoveTupleAsync(string DwFlag, string Dx, string Dy, string DwData, string DwExtraInfo) {
            this.MouseMoveTupleAsync(DwFlag, Dx, Dy, DwData, DwExtraInfo, null);
        }
        
        public void MouseMoveTupleAsync(string DwFlag, string Dx, string Dy, string DwData, string DwExtraInfo, object userState) {
            if ((this.onBeginMouseMoveTupleDelegate == null)) {
                this.onBeginMouseMoveTupleDelegate = new BeginOperationDelegate(this.OnBeginMouseMoveTuple);
            }
            if ((this.onEndMouseMoveTupleDelegate == null)) {
                this.onEndMouseMoveTupleDelegate = new EndOperationDelegate(this.OnEndMouseMoveTuple);
            }
            if ((this.onMouseMoveTupleCompletedDelegate == null)) {
                this.onMouseMoveTupleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMouseMoveTupleCompleted);
            }
            base.InvokeAsync(this.onBeginMouseMoveTupleDelegate, new object[] {
                        DwFlag,
                        Dx,
                        Dy,
                        DwData,
                        DwExtraInfo}, this.onEndMouseMoveTupleDelegate, this.onMouseMoveTupleCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent CreateChannel() {
            return new MouseEventClientChannel(this);
        }
        
        private class MouseEventClientChannel : ChannelBase<TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent>, TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent {
            
            public MouseEventClientChannel(System.ServiceModel.ClientBase<TrackPadSilverlight.WindowsPhoneMouseService.IMouseEvent> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginMouseMoveTuple(string DwFlag, string Dx, string Dy, string DwData, string DwExtraInfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = DwFlag;
                _args[1] = Dx;
                _args[2] = Dy;
                _args[3] = DwData;
                _args[4] = DwExtraInfo;
                System.IAsyncResult _result = base.BeginInvoke("MouseMoveTuple", _args, callback, asyncState);
                return _result;
            }
            
            public void EndMouseMoveTuple(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("MouseMoveTuple", _args, result);
            }
        }
    }
}
