'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace serviceSQL
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SqlDataIn", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFhostVBnet"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SqlDataIn
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SqlParamField As System.Collections.Generic.Dictionary(Of String, Object)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SqlTextField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SqlTypeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SqlParam() As System.Collections.Generic.Dictionary(Of String, Object)
            Get
                Return Me.SqlParamField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SqlParamField, value) <> true) Then
                    Me.SqlParamField = value
                    Me.RaisePropertyChanged("SqlParam")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SqlText() As String
            Get
                Return Me.SqlTextField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SqlTextField, value) <> true) Then
                    Me.SqlTextField = value
                    Me.RaisePropertyChanged("SqlText")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SqlType() As String
            Get
                Return Me.SqlTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SqlTypeField, value) <> true) Then
                    Me.SqlTypeField = value
                    Me.RaisePropertyChanged("SqlType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SqlDataOut", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFhostVBnet"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SqlDataOut
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataSetOutField As System.Data.DataSet
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private intOutField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private strErrorField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DataSetOut() As System.Data.DataSet
            Get
                Return Me.DataSetOutField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataSetOutField, value) <> true) Then
                    Me.DataSetOutField = value
                    Me.RaisePropertyChanged("DataSetOut")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property intOut() As Integer
            Get
                Return Me.intOutField
            End Get
            Set
                If (Me.intOutField.Equals(value) <> true) Then
                    Me.intOutField = value
                    Me.RaisePropertyChanged("intOut")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property strError() As String
            Get
                Return Me.strErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.strErrorField, value) <> true) Then
                    Me.strErrorField = value
                    Me.RaisePropertyChanged("strError")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="serviceSQL.ISqlServiceContract")>  _
    Public Interface ISqlServiceContract
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISqlServiceContract/GetDataSet", ReplyAction:="http://tempuri.org/ISqlServiceContract/GetDataSetResponse")>  _
        Function GetDataSet(ByVal root As serviceSQL.SqlDataIn) As serviceSQL.SqlDataOut
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISqlServiceContract/GetDataSet", ReplyAction:="http://tempuri.org/ISqlServiceContract/GetDataSetResponse")>  _
        Function GetDataSetAsync(ByVal root As serviceSQL.SqlDataIn) As System.Threading.Tasks.Task(Of serviceSQL.SqlDataOut)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISqlServiceContract/ExecuteSqlNonQuery", ReplyAction:="http://tempuri.org/ISqlServiceContract/ExecuteSqlNonQueryResponse")>  _
        Function ExecuteSqlNonQuery(ByVal root As serviceSQL.SqlDataIn) As serviceSQL.SqlDataOut
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISqlServiceContract/ExecuteSqlNonQuery", ReplyAction:="http://tempuri.org/ISqlServiceContract/ExecuteSqlNonQueryResponse")>  _
        Function ExecuteSqlNonQueryAsync(ByVal root As serviceSQL.SqlDataIn) As System.Threading.Tasks.Task(Of serviceSQL.SqlDataOut)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISqlServiceContract/ServiceOK", ReplyAction:="http://tempuri.org/ISqlServiceContract/ServiceOKResponse")>  _
        Function ServiceOK() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISqlServiceContract/ServiceOK", ReplyAction:="http://tempuri.org/ISqlServiceContract/ServiceOKResponse")>  _
        Function ServiceOKAsync() As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISqlServiceContractChannel
        Inherits serviceSQL.ISqlServiceContract, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SqlServiceContractClient
        Inherits System.ServiceModel.ClientBase(Of serviceSQL.ISqlServiceContract)
        Implements serviceSQL.ISqlServiceContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetDataSet(ByVal root As serviceSQL.SqlDataIn) As serviceSQL.SqlDataOut Implements serviceSQL.ISqlServiceContract.GetDataSet
            Return MyBase.Channel.GetDataSet(root)
        End Function
        
        Public Function GetDataSetAsync(ByVal root As serviceSQL.SqlDataIn) As System.Threading.Tasks.Task(Of serviceSQL.SqlDataOut) Implements serviceSQL.ISqlServiceContract.GetDataSetAsync
            Return MyBase.Channel.GetDataSetAsync(root)
        End Function
        
        Public Function ExecuteSqlNonQuery(ByVal root As serviceSQL.SqlDataIn) As serviceSQL.SqlDataOut Implements serviceSQL.ISqlServiceContract.ExecuteSqlNonQuery
            Return MyBase.Channel.ExecuteSqlNonQuery(root)
        End Function
        
        Public Function ExecuteSqlNonQueryAsync(ByVal root As serviceSQL.SqlDataIn) As System.Threading.Tasks.Task(Of serviceSQL.SqlDataOut) Implements serviceSQL.ISqlServiceContract.ExecuteSqlNonQueryAsync
            Return MyBase.Channel.ExecuteSqlNonQueryAsync(root)
        End Function
        
        Public Function ServiceOK() As String Implements serviceSQL.ISqlServiceContract.ServiceOK
            Return MyBase.Channel.ServiceOK
        End Function
        
        Public Function ServiceOKAsync() As System.Threading.Tasks.Task(Of String) Implements serviceSQL.ISqlServiceContract.ServiceOKAsync
            Return MyBase.Channel.ServiceOKAsync
        End Function
    End Class
End Namespace
